### ISSUE TITLE
Option to Drop NHD Segments by ftype and NHDid

### ISSUE THREAD

**Issue by michelob23** [DOI-USGS/sfrmaker#134]
Thanks for this great tool. It would be nice to have the capability to drop NHD segments by ftype (e.g., 428) and NHDid, similar to the "drop_fcodes" option in the from_nhdplus_hr() method.  

I've attached my "lines.py" and "nhdplus_utils.py" that have this implemented. 
[uploads.zip](https://github.com/DOI-USGS/sfrmaker/files/10238373/uploads.zip)

**Comment by aleaf** [comment]
Hi @michelob23 , thanks for raising this issue. Would you be willing to submit a pull request? Basically you would commit your changes and push them to your fork, and then from there you can submit a pull request via GitHub (more info: https://doi-usgs.github.io/sfrmaker/latest/contributing.html). Then you would get credit for adding this feature.

**Comment by michelob23** [comment]
Sounds good, will do!

**Comment by aleaf** [comment]
fixed in v0.9.4
