### ISSUE TITLE
Lines.from_nhdplus_v2 with downstream divergences causes numpy error

### ISSUE THREAD

**Issue by janetrbarclay** [DOI-USGS/sfrmaker#140]
I am working in a coastal environment where reaches commonly have downstream divergences (multiple toid's). 

**Previously (python = 3.8, numpy=1.20.2, sfrmaker = 0.7.0)** when I generated a lns object
`lns = sfrmaker.Lines.from_nhdplus_v2(NHDPlus_paths=NHDPlus_paths, filter="clip_box.shp")`
NHD vpu = '01' (NE)
[clip_box.zip](https://github.com/DOI-USGS/sfrmaker/files/10558819/clip_box.zip)
 
I would get this deprecation warning but could generate the SFR inputs.
```
VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences 
(which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. 
If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
return array(a, dtype, copy=False, order=order)
```

**After upgrading my conda environment (python = 3.11, numpy = 1.24.1, sfrmaker=0.9.4)** the same call produces this error:
```
load finished in 33.15s

Getting routing information from NHDPlus Plusflow table...
finished in 1.57s

Traceback (most recent call last):

  File ~\.conda\envs\lis_compound_flooding_2023\Lib\site-packages\numpy\core\fromnumeric.py:1565 in squeeze
    squeeze = a.squeeze

AttributeError: 'list' object has no attribute 'squeeze'


During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  Cell In[196], line 1
    lns = sfrmaker.Lines.from_nhdplus_v2(NHDPlus_paths=NHDPlus_paths, filter ="clip_box.shp")

  File ~\.conda\envs\lis_compound_flooding_2023\Lib\site-packages\sfrmaker\lines.py:664 in from_nhdplus_v2
    return cls.from_dataframe(df, id_column='COMID',

  File ~\.conda\envs\lis_compound_flooding_2023\Lib\site-packages\sfrmaker\lines.py:589 in from_dataframe
    return cls(df, attr_length_units=attr_length_units,

  File ~\.conda\envs\lis_compound_flooding_2023\Lib\site-packages\sfrmaker\lines.py:88 in __init__
    self._original_routing = self.routing.copy()

  File ~\.conda\envs\lis_compound_flooding_2023\Lib\site-packages\sfrmaker\lines.py:134 in routing
    to_one = is_to_one(toid)

  File ~\.conda\envs\lis_compound_flooding_2023\Lib\site-packages\sfrmaker\checks.py:52 in is_to_one
    squeezed = np.squeeze(list(toid_sequence))

  File <__array_function__ internals>:200 in squeeze

  File ~\.conda\envs\lis_compound_flooding_2023\Lib\site-packages\numpy\core\fromnumeric.py:1567 in squeeze
    return _wrapit(a, 'squeeze', axis=axis)

  File ~\.conda\envs\lis_compound_flooding_2023\Lib\site-packages\numpy\core\fromnumeric.py:43 in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (31197,) + inhomogeneous part.
```

**Comment by aleaf** [comment]
Hi @janetrbarclay, this script is working locally for me:
```
import sfrmaker

NHDPlus_paths = ['<path to NHDPlus folders>/' + 'NHDPlusNE/NHDPlus01/']
lines = sfrmaker.Lines.from_nhdplus_v2(NHDPlus_paths=NHDPlus_paths, bbox_filter="clip_box.shp")
lines.write_shapefile('lines.shp')
```
(with sfrmaker 0.10.0, python 3.10.8, numpy 1.23.5; not sure what other versions could matter but I re-built my python distribution a month or two ago).

Maybe try updating your python, using mambaforge if necessary (note the discussion about the various options and best practices [here](https://aleaf.github.io/sfrmaker/latest/installation.html#installing-python-dependencies-with-conda). Otherwise, if you're running this in a Jupyter Notebook, it could be that the kernel there isn't using the right environment (the SFRmaker install instructions also have a section on how to install the Jupyter Notebook kernel).

**Comment by janetrbarclay** [comment]
Hi @aleaf, thanks for looking into this. Based on what you mentioned and a few tests I ran this AM (details below), it seems the issue is with the newest version of numpy.  (afterward I found these [dev notes](https://numpy.org/devdocs/release/1.19.0-notes.html#deprecations) indicating the ability to make an array from nested ragged sequences was deprecated in numpy 1.19 and expired in [numpy 1.24](https://numpy.org/devdocs/release/1.24.0-notes.html#expired-deprecations)) 

At this point I can easily roll back to np 1.23 and run my scripts for now but let me know if I can be help with any more troubleshooting.

**Things I tried:** 
I tried 4 different combinations of python / numpy / sfrmaker / fiona versions (all on a windows machine) and ran the following script from the console:

```
from osgeo import gdal
import sfrmaker
import sys
import os


NHDPlus_paths = sys.argv[1]
CONDA_env = os.environ['CONDA_DEFAULT_ENV']

if sfrmaker.__version__ == "0.10.0":
    lines = sfrmaker.Lines.from_nhdplus_v2(NHDPlus_paths=NHDPlus_paths, bbox_filter="clip_box.shp")
else:
    lines = sfrmaker.Lines.from_nhdplus_v2(NHDPlus_paths=NHDPlus_paths, filter="clip_box.shp")
lines.write_shapefile('lines_{}.shp'.format(CONDA_env))
```

**Here's a summary of the results:**
![image](https://user-images.githubusercontent.com/3833808/216667308-9637130c-fc5b-499e-9381-369f0ddfa431.png)

Figure 1 Deprecation warning from test_sfrmaker_2
![image](https://user-images.githubusercontent.com/3833808/216667452-fb3ba3a3-1942-49d8-bb9d-2d62e77488e1.png)

Figure 2. Error message from test_sfrmaker_3
![image](https://user-images.githubusercontent.com/3833808/216667475-0655e77c-bcf5-4ada-a6cd-f835b0a47d20.png)

Figure 3 Error message from test_sfrmaker_4
![image](https://user-images.githubusercontent.com/3833808/216667496-e0d2a5ac-32fd-4047-87d4-2259b2a24702.png)


Re: your suggestion about the jupyter kernel, I'm not using a jupyter notebook - I'm developing a snakemake workflow and doing the development work in Spyder.

**Comment by aleaf** [comment]
Hi @janetrbarclay, thanks for digging into this. I ran the tests with numpy 1.24 and I think I was able to reproduce your issue (and uncovered a few more). I just pushed some fixes. Can you pull from the develop branch and confirm that this is fixed? Thanks!

**Comment by aleaf** [comment]
Hi @janetrbarclay, I think you need to replace `git://` with `https://`. This is a somewhat recent change to GitHub that applies to any pip install from a branch using this git+ format.

**Comment by janetrbarclay** [comment]
@aleaf . Thanks! The git install and the generating the sfrmaker lines both worked fine for me this time.

I'm guessing you saw these as well, but I do have deprecation warnings for disutils Version classes from gisutils and for ReadingError from rasterstats.

Also, I copied the prior command for pulling the develop branch from the sfrmaker docs, so you'll want to update it [there](https://aleaf.github.io/sfrmaker/latest/installation.html#installing-the-latest-develop-version-of-sfrmaker). 

Thanks again for your help (and for making this package - it's super useful!)

**Comment by aleaf** [comment]
Thanks for brining that to my attention. Will update the docs. Glad you got it working.
